### ISSUE TITLE
Could I use this lib to solve my problem?

### ISSUE THREAD

**Issue by timmolter** [odinsbane/least-squares-in-java#1]
Hi, Just asking for your opinion if this lib would suffice for my specific problem. I looked at https://github.com/odinsbane/least-squares-in-java/blob/master/src/test/java/org/orangepalantir/leastsquares/fitters/NonLinearSolverTest.java, but I am still wondering. I posted my problem on StackOverflow and one comment led me here: 

http://stackoverflow.com/q/35701194/1625820

**Comment by odinsbane** [comment]
I think it could, but you would have to rephrase the problem a little bit. The least squares fitting algorithm will try to minimize the error between the input z values and the output. If you think of your a,b,c,d and e as your input values, then think of x, y and z as your output values. The problem is that the second two equations use the same input vectors. You might need to square them and combine them.

**Comment by timmolter** [comment]
a,b,c,d and e are just constants. What I'm trying to solve for is θ0, θ1, θ2 given X,Y, and Z. Can you suggest how I would set that up?

**Comment by odinsbane** [comment]
You would create some strange function.

```
Function f = new Function(){
           public double evaluate(double[] values, double[] parameters){
               double θ1 = parameters[0];
               double θ2 = parameters[1];

               if(values[0]==-1){
                   return a - e + bcosθ1 + csinθ1 + d*cosθ2sinθ1 + dsinθ2;
              } else if(values[0]==0){
                  return ( bsinθ1 + ccosθ1 + d*cosθ2*cosθ1 ) * sinθ0;
             } else{
                  return ( bsinθ1 + ccosθ1 + d*cosθ2*cosθ1 ) * cosθ0;
            }
          }
    public int getNParameters(){
           return 2;
    }
    public int getNInputs(){
          return 1;
    }

   }
```

Then your input arrays would be.

```
double[][] xs = {{-1}, {0}, {1}};
double[] zs = {z, x, y};
```

**Comment by odinsbane** [comment]
Oops, I didn't see there were three thetas. I actually think your problem isn't defined well enough. Note that x^2 + y^2 = ( bsinθ1 + ccosθ1 + d_cosθ2_cosθ1 )^2 which means that θ0 can be any value.

**Comment by odinsbane** [comment]
Sorry, not any value. You can solve for theta0 before you begin since you know x and y.

**Comment by timmolter** [comment]
Thanks for the help! I'll give it a try I think. Yes, I could solve for theta0 for the 2nd and third equations and set them equal to each other, then I'd only have two equations left with theta1 and theta2. Solve that system of two equations and then plug in theta 1 and theta2 to solve for theta 0. Is that what you mean?

**Comment by odinsbane** [comment]
```
import org.orangepalantir.leastsquares.Fitter;
import org.orangepalantir.leastsquares.Function;
import org.orangepalantir.leastsquares.fitters.NonLinearSolver;

import java.util.Arrays;

/**
 */
public class JunkClass {
    static double a = 1;
    static double b = 1;
    static double c = 1;
    static double d = 1;
    static double e = 1;

    static double x = 0.5;
    static double y = 0.1;
    static double z = 1.0;
    public static void main(String[] args){

        double[][] xs = {{-1}, {0}, {1}};

        double[] zs = {z, x, y};

        double r = Math.sqrt(x*x + y*y);
        final double sinTheta0 = x/r;
        final double cosTheta0 = y/r;


        Function f = new Function(){

            @Override
            public double evaluate(double[] values, double[] parameters) {
                double t1 = parameters[0];
                double t2 = parameters[1];
                if(values[0] == -1){
                    return a - e + b*Math.cos(t1) + c*Math.sin(t1) + d*Math.cos(t2)*Math.sin(t1) + d*Math.sin(t2);

                } else if(values[0]==0){
                    return ( b*Math.sin(t1) + c*Math.cos(t1) + d*Math.cos(t2)*Math.cos(t1))*sinTheta0;
                } else{
                    return ( b*Math.sin(t1) + c*Math.cos(t1) + d*Math.cos(t2)*Math.cos(t1))*cosTheta0;
                }
            }

            @Override
            public int getNParameters() {
                return 2;
            }

            @Override
            public int getNInputs() {
                return 1;
            }
        };

        Fitter fit = new NonLinearSolver(f);
        fit.setData(xs, zs);
        double[] params = {0,0};
        fit.setParameters(params);

        fit.fitData();

        System.out.println(Arrays.toString(fit.getParameters()));



    }

    private static double square(double v) {
        return v*v;
    }
}

```

I did not check the results.

**Comment by timmolter** [comment]
Wow, thanks! Testing now...

**Comment by timmolter** [comment]
It worked! Thanks again. Is there any way to seed initial values for θ0, θ1, θ2?

**Comment by odinsbane** [comment]
When I call set parameters, those are the initial values for theta 1 and
theta 2.

**Comment by timmolter** [comment]
@odinsbane Are you interested in posting your answer on StackOverflow so I can accept it? If not, I'll answer it myself. But I wanted to let you get the credit first if you want.

**Comment by odinsbane** [comment]
I checked, and the question is on hold. If you can provide an answer feel
free.

Cheers
mbs

**Comment by timmolter** [comment]
Thanks again for your help!
